version: '3'
services:
  bedrock-server:
    image: u7chan/bedrock-server
    container_name: minecraft-bedrock-server
    build:
      context: .
      dockerfile: ./bedrock-server/Dockerfile
      args:
        - VERSION=1.19.1.01
    ports:
      - 19132:19132/udp
    volumes:
      - ./worlds:/home/worlds
    env_file:
      - .env
